server_name: Centre for Genomic Regulation
base_url: https://genome.crg.cat/rnaget/
token: SERVER_API_KEY_CRG
implemented:
    projects: true
    studies: true
    expressions: true
    continuous: true